#!/bin/bash

BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

ln -s ${BASEDIR}/.bashrc ~/.bashrc
ln -s ${BASEDIR}/.profile ~/.profile
ln -s ${BASEDIR}/.vimrc ~/.vimrc
ln -s ${BASEDIR}/.tmux.conf ~/.tmux.conf
