#!/bin/bash

BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

dotfiles=(
  .bashrc
  .condarc
  .gitignore
  .profile
  .tmux.conf
  .vim
  .vimrc
)

mkdir -p ~/.dotfiles_bkp

for i in ${dotfiles[@]}; do
  if [ -f ~/$i ]; then
    mv ~/$i ~/.dotfiles_bkp/$i
  fi
  ln -s ${BASEDIR}/$i ~/$i
done
